
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // MISIÓN 1: NEW GREETINGS & SOCIAL
  { id: 1, mission: 1, text: "Spider-Man says: 'Thank ________' for the help!", options: ["you", "your", "yours", "me", "us"], correctAnswer: "you", hint: "Es el pronombre para 'ti'.", translation: "Thank you (Gracias)", explanation: "Usamos 'you' después de un verbo para referirnos a la persona a la que hablamos." },
  { id: 2, mission: 1, text: "Bowser is not good. He is ________.", options: ["bad", "bed", "bat", "back", "big"], correctAnswer: "bad", hint: "Suena parecido a 'bed' pero termina en D.", translation: "Bad (Malo)", explanation: "Bad es el adjetivo para alguien malvado." },
  { id: 3, mission: 1, text: "Mario asks: 'How ________ are you?' - I am 10.", options: ["old", "gold", "cold", "long", "tall"], correctAnswer: "old", hint: "Se usa para preguntar la edad.", translation: "How old are you? (¿Cuántos años tienes?)", explanation: "En inglés no 'tenemos' años, 'somos' viejos (old)." },
  { id: 4, mission: 1, text: "The Hulk is very ________, not small.", options: ["big", "pig", "bag", "dig", "bug"], correctAnswer: "big", hint: "Empieza con B y rima con 'pig'.", translation: "Big (Grande)", explanation: "Big describe algo de gran tamaño." },
  { id: 5, mission: 1, text: "I have a big ________. My mom and my dad.", options: ["family", "famous", "familiar", "farmer", "father"], correctAnswer: "family", hint: "Grupo de personas que viven juntas.", translation: "Family (Familia)", explanation: "La familia son tus seres queridos cercanos." },
  { id: 6, mission: 1, text: "Captain America says: 'Please, ________ me'.", options: ["help", "held", "hello", "hell", "hope"], correctAnswer: "help", hint: "Lo que pides cuando estás en problemas.", translation: "Help (Ayuda)", explanation: "Help es socorro o asistencia." },
  { id: 7, mission: 1, text: "Is she a girl? No, she is a ________.", options: ["woman", "women", "man", "worm", "winner"], correctAnswer: "woman", hint: "Una mujer adulta.", translation: "Woman (Mujer)", explanation: "Woman es singular (una), women es plural (muchas)." },
  { id: 8, mission: 1, text: "In Minecraft, Steve is a ________.", options: ["boy", "toy", "buy", "box", "bye"], correctAnswer: "boy", hint: "Rima con 'toy'.", translation: "Boy (Niño/Chico)", explanation: "Boy se refiere a un niño o joven masculino." },
  { id: 9, mission: 1, text: "It is 9:00 PM. I say: 'Good ________'.", options: ["night", "eight", "right", "light", "fight"], correctAnswer: "night", hint: "Lo que ves cuando sale la luna.", translation: "Good night (Buenas noches)", explanation: "Se usa para despedirse al final del día." },
  { id: 10, mission: 1, text: "Iron Man is very ________ and smart.", options: ["rich", "reach", "rice", "rock", "rush"], correctAnswer: "rich", hint: "Tiene muchísimas monedas.", translation: "Rich (Rico)", explanation: "Alguien con mucho dinero es 'rich'." },

  // MISIÓN 2: NEW FOOD & HOUSE
  { id: 11, mission: 2, text: "I want a sweet ________ with chips.", options: ["cookie", "cook", "cake", "coke", "cone"], correctAnswer: "cookie", hint: "Galleta deliciosa.", translation: "Cookie (Galleta)", explanation: "Cookie es el término para galleta dulce." },
  { id: 12, mission: 2, text: "Minions love to eat ________.", options: ["bananas", "bandanas", "beans", "berries", "bread"], correctAnswer: "bananas", hint: "Es amarilla y rima con 'bandanas'.", translation: "Banana (Plátano)", explanation: "Fruta tropical favorita de los Minions." },
  { id: 13, mission: 2, text: "I eat ________ and beans for lunch.", options: ["rice", "race", "rise", "rich", "rock"], correctAnswer: "rice", hint: "Granos blancos muy comunes.", translation: "Rice (Arroz)", explanation: "Rice es el cereal blanco que comemos mucho." },
  { id: 14, mission: 2, text: "Thor drinks orange ________.", options: ["juice", "just", "june", "jump", "joke"], correctAnswer: "juice", hint: "Líquido que sale de la fruta.", translation: "Juice (Jugo/Zumo)", explanation: "Juice es zumo de fruta." },
  { id: 15, mission: 2, text: "Minecraft: I put the bed in the ________.", options: ["bedroom", "bathroom", "ballroom", "backroom", "boardroom"], correctAnswer: "bedroom", hint: "La pieza donde duermes.", translation: "Bedroom (Dormitorio)", explanation: "Bed (cama) + Room (habitación) = Bedroom." },
  { id: 16, mission: 2, text: "I like ________ on my bread.", options: ["cheese", "choose", "chess", "chase", "cheer"], correctAnswer: "cheese", hint: "Es amarillo y lo comen los ratones.", translation: "Cheese (Queso)", explanation: "Cheese es el lácteo que va bien con la pizza." },
  { id: 17, mission: 2, text: "The kitchen has a big ________.", options: ["fridge", "bridge", "freeze", "frame", "friend"], correctAnswer: "fridge", hint: "Mantiene la comida fría.", translation: "Fridge (Nevera)", explanation: "Fridge es la abreviación de refrigerator." },
  { id: 18, mission: 2, text: "I want an ________ for breakfast.", options: ["egg", "eye", "ear", "end", "eat"], correctAnswer: "egg", hint: "Viene en un cascarón blanco.", translation: "Egg (Huevo)", explanation: "Egg es el alimento que ponen las aves." },
  { id: 19, mission: 2, text: "Mario eats a red ________ to grow.", options: ["mushroom", "music", "museum", "mountain", "muffin"], correctAnswer: "mushroom", hint: "Parece un paraguas pequeño.", translation: "Mushroom (Champiñón)", explanation: "El clásico hongo de poder de Mario." },
  { id: 20, mission: 2, text: "I cook food in the ________.", options: ["kitchen", "chicken", "kitten", "kitchener", "kicking"], correctAnswer: "kitchen", hint: "Se parece a la palabra 'chicken' (pollo).", translation: "Kitchen (Cocina)", explanation: "Lugar de la casa dedicado a cocinar." },

  // MISIÓN 3: NEW ACTION ROUTINES
  { id: 21, mission: 3, text: "I ________ my face in the morning.", options: ["wash", "watch", "wish", "walk", "wait"], correctAnswer: "wash", hint: "Usar agua para estar limpio.", translation: "Wash (Lavar)", explanation: "Wash es la acción de limpiar con agua." },
  { id: 22, mission: 3, text: "Spider-Man can ________ buildings.", options: ["climb", "clean", "claim", "click", "clear"], correctAnswer: "climb", hint: "Subir usando manos y pies.", translation: "Climb (Escalar)", explanation: "Climb se usa para subir montañas o muros." },
  { id: 23, mission: 3, text: "I ________ my clothes in the morning.", options: ["wear", "were", "where", "war", "ear"], correctAnswer: "wear", hint: "Ponerse la ropa encima.", translation: "Wear (Vestir)", explanation: "Wear es el verbo para usar ropa." },
  { id: 24, mission: 3, text: "Mario can ________ very high.", options: ["jump", "lamp", "pump", "dump", "camp"], correctAnswer: "jump", hint: "Impulsarse hacia arriba.", translation: "Jump (Saltar)", explanation: "Jump es despegar los pies del suelo." },
  { id: 25, mission: 3, text: "I ________ my toys after playing.", options: ["clean", "clear", "close", "cloud", "clown"], correctAnswer: "clean", hint: "Dejar algo sin suciedad.", translation: "Clean (Limpiar)", explanation: "Clean es asear o recoger." },
  { id: 26, mission: 3, text: "Flash is fast. He doesn't ________.", options: ["walk", "talk", "work", "wake", "wall"], correctAnswer: "walk", hint: "Ir a paso lento.", translation: "Walk (Caminar)", explanation: "Walk es desplazarse a pie normalmente." },
  { id: 27, mission: 3, text: "I ________ TV in the living room.", options: ["watch", "wash", "witch", "water", "witch"], correctAnswer: "watch", hint: "Mirar algo por mucho tiempo.", translation: "Watch (Ver/Mirar)", explanation: "Watch se usa para pantallas o espectáculos." },
  { id: 28, mission: 3, text: "Iron Man can ________ in the sky.", options: ["fly", "fry", "flu", "sky", "try"], correctAnswer: "fly", hint: "Lo que hacen los pájaros.", translation: "Fly (Volar)", explanation: "Fly es moverse por el aire." },
  { id: 29, mission: 3, text: "I ________ with my dog in the park.", options: ["play", "pray", "pay", "plan", "plot"], correctAnswer: "play", hint: "Hacer algo divertido.", translation: "Play (Jugar)", explanation: "Play es recrearse con juegos." },
  { id: 30, mission: 3, text: "Minecraft: I ________ a hole in the ground.", options: ["dig", "dog", "pig", "big", "day"], correctAnswer: "dig", hint: "Hacer un hoyo.", translation: "Dig (Cavar)", explanation: "Dig es remover tierra para hacer un hueco." },

  // MISIÓN 4: NEW ABILITIES & COLORS
  { id: 31, mission: 4, text: "Hulk is ________, not red.", options: ["green", "greet", "great", "grain", "grey"], correctAnswer: "green", hint: "Color de los árboles.", translation: "Green (Verde)", explanation: "Green es el color esmeralda." },
  { id: 32, mission: 4, text: "Captain America's shield is ________, white and blue.", options: ["red", "read", "ride", "road", "rod"], correctAnswer: "red", hint: "Color de la sangre.", translation: "Red (Rojo)", explanation: "Red es el color del fuego." },
  { id: 33, mission: 4, text: "I can ________ a beautiful song.", options: ["sing", "sink", "sign", "sun", "song"], correctAnswer: "sing", hint: "Hacer música con la voz.", translation: "Sing (Cantar)", explanation: "Sing es el verbo de la música vocal." },
  { id: 34, mission: 4, text: "The sky is ________ today.", options: ["blue", "blow", "blew", "glue", "clue"], correctAnswer: "blue", hint: "Color del océano.", translation: "Blue (Azul)", explanation: "Blue es el color del cielo despejado." },
  { id: 35, mission: 4, text: "I use a ________ to use the internet.", options: ["computer", "company", "compare", "complete", "compute"], correctAnswer: "computer", hint: "Máquina para estudiar y jugar.", translation: "Computer (Computadora)", explanation: "Computer es el ordenador personal." },
  { id: 36, mission: 4, text: "Can you ________ a tree?", options: ["paint", "point", "pant", "print", "pain"], correctAnswer: "paint", hint: "Usar colores en un papel.", translation: "Paint (Pintar)", explanation: "Paint es crear arte con pintura." },
  { id: 37, mission: 4, text: "Spider-Man is very ________.", options: ["strong", "string", "strange", "storm", "wrong"], correctAnswer: "strong", hint: "Que tiene mucho poder físico.", translation: "Strong (Fuerte)", explanation: "Strong es lo opuesto a débil (weak)." },
  { id: 38, mission: 4, text: "I ________ movies at the cinema.", options: ["see", "sea", "say", "sun", "sit"], correctAnswer: "see", hint: "Usar los ojos.", translation: "See (Ver)", explanation: "See es percibir con la vista." },
  { id: 39, mission: 4, text: "Is the mouse small? Yes, it is ________.", options: ["small", "smell", "smile", "smart", "shall"], correctAnswer: "small", hint: "Poquito tamaño.", translation: "Small (Pequeño)", explanation: "Small es diminuto." },
  { id: 40, mission: 4, text: "I like to ________ pictures of superheroes.", options: ["color", "collar", "cooler", "cover", "cloud"], correctAnswer: "color", hint: "Rellenar con lápices de colores.", translation: "Color (Colorear)", explanation: "Color es dar tonalidades a un dibujo." },

  // MISIÓN 5: NEW FEELINGS & BODY PARTS
  { id: 41, mission: 5, text: "Hulk gets ________ when he fights.", options: ["angry", "hungry", "happy", "ugly", "only"], correctAnswer: "angry", hint: "Muy, muy molesto.", translation: "Angry (Enojado)", explanation: "Angry es sentir mucha rabia." },
  { id: 42, mission: 5, text: "Thor has long blonde ________.", options: ["hair", "air", "heir", "ear", "here"], correctAnswer: "hair", hint: "Lo que crece en tu cabeza.", translation: "Hair (Cabello)", explanation: "Hair es el pelo humano." },
  { id: 43, mission: 5, text: "I use my ________ to clap.", options: ["hands", "heads", "horns", "hairs", "handsom"], correctAnswer: "hands", hint: "Están al final de tus brazos.", translation: "Hands (Manos)", explanation: "Hands son las extremidades para agarrar." },
  { id: 44, mission: 5, text: "Mario has a big ________.", options: ["nose", "noise", "none", "nice", "note"], correctAnswer: "nose", hint: "En el medio de la cara.", translation: "Nose (Nariz)", explanation: "Nose es para oler y respirar." },
  { id: 45, mission: 5, text: "I am ________. I want to cry.", options: ["sad", "said", "sand", "side", "say"], correctAnswer: "sad", hint: "Sentirse bajoneado.", translation: "Sad (Triste)", explanation: "Sad es la emoción de infelicidad." },
  { id: 46, mission: 5, text: "I have white ________ in my mouth.", options: ["teeth", "tooth", "truth", "tenth", "tent"], correctAnswer: "teeth", hint: "Sirven para masticar.", translation: "Teeth (Dientes)", explanation: "Teeth es el plural de tooth." },
  { id: 47, mission: 5, text: "The ice is very ________.", options: ["cold", "could", "called", "gold", "hold"], correctAnswer: "cold", hint: "Temperatura muy baja.", translation: "Cold (Frío)", explanation: "Cold es lo opuesto a hot." },
  { id: 48, mission: 5, text: "The sun is very ________.", options: ["hot", "hat", "hit", "hop", "hut"], correctAnswer: "hot", hint: "Quema mucho.", translation: "Hot (Caliente)", explanation: "Hot es alta temperatura." },
  { id: 49, mission: 5, text: "I use my ________ to think.", options: ["head", "hand", "hear", "hard", "help"], correctAnswer: "head", hint: "Donde está el cerebro.", translation: "Head (Cabeza)", explanation: "Head es la parte superior del cuerpo." },
  { id: 50, mission: 5, text: "I am ________! I want to jump and laugh!", options: ["excited", "exited", "exercise", "example", "exactly"], correctAnswer: "excited", hint: "Muy feliz y con energía.", translation: "Excited (Emocionado)", explanation: "Excited es estar con mucha expectativa positiva." }
];
